### PR TITLE
Add Hyperlink

### PR DESCRIPTION
**Pull request by steveyiyo**
- [架構文件](architecture/network.md)
- [Architecture](architecture/network.md)

### CODE REVIEW

**Review by ching-kuo — CHANGES_REQUESTED** [review]
The link only includes network architecture. IMO, it's better to add a list bellow and link to different docs.

**Comment by steveyiyo** [comment]
@iGene, Thanks for your feedback. I have updated it.

**Comment by ching-kuo** [comment]
Sorry for being unclear, I meant a sublist under the original title.

**Comment by steveyiyo** [comment]
@iGene Thanks, I have updated it.

**Pull request merged**
